[tool.poetry]
name = "aloy"
version = "0.1.0"
description = ""
authors = ["Elias Soltani <elias.soltani@fuel50.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
